language: php

dist: trusty

env:
  global:
    - TRAVIS_NODE_VERSION="10"
    - MODULE_NAME="webauthn-authenticator"

matrix:
  include:
    - php: 7.1
      env: DB=PGSQL CORE_RELEASE=3.7 PHPCS_TEST=1 PHPUNIT_TEST=1
    - php: 7.2
      env: DB=MYSQL CORE_RELEASE=3.7 NPM_TEST=1
    - php: 7.3
      env: DB=MYSQL CORE_RELEASE=3.7 PHPUNIT_COVERAGE_TEST=1

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  # Install composer
  - composer validate
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

  # Install NPM dependencies
  - if [[ $NPM_TEST ]]; then (cd $MODULE_NAME && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION && npm install -g yarn && yarn install --network-concurrency 1 && yarn run build); fi

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit $MODULE_NAME; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml $MODULE_NAME; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs $MODULE_NAME/src/ $MODULE_NAME/tests/; fi
  - if [[ $NPM_TEST ]]; then (cd $MODULE_NAME && git diff-files --quiet -w --relative=client); fi
  - if [[ $NPM_TEST ]]; then (cd $MODULE_NAME && git diff --name-status --relative=client); fi
  - if [[ $NPM_TEST ]]; then (cd $MODULE_NAME && yarn run coverage); fi
  - if [[ $NPM_TEST ]]; then (cd $MODULE_NAME && yarn run lint); fi
